apiVersion: kustomize.config.k8s.io/v1beta1
kind: kuntomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: riquena96/gitopsfc
  newTag: 945a5f8bd6183f8633dc04f1673949cd71dc19aa
